In [1]:
# Imports
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Load the data
plays_df = pd.read_csv('/Users/JKMacBook/Documents/Lambda/Kaggle/NFL/nfl-big-data-bowl-2021/full_play_3.csv')

In [3]:
# The plays df
plays_df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,...,week,def,defender,manZone,scheme,route,startDist,endDist,covDist,closeSpeed
0,0,0,0,2018090600,75,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,...,1,PHI,Malcolm Jenkins,zone,cover-3,HITCH,7.768739,2.957871,10.726609,4.369544
1,1,1,1,2018090600,146,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,...,1,PHI,Jordan Hicks,zone,cover-3,HITCH,4.346631,1.891719,6.238350,4.909824
2,2,2,2,2018090600,168,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,...,1,PHI,Sidney Jones,man,cover-1,NaN,NaN,NaN,NaN,NaN
3,3,3,3,2018090600,190,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,...,1,PHI,Ronald Darby,man,cover-1,CORNER,12.974671,3.898949,16.873620,5.341803
4,4,4,4,2018090600,256,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,...,1,PHI,Malcolm Jenkins,man,cover-0,GO,1.053803,4.464135,5.517937,-3.789258

In [4]:
# Check shape of plays df
plays_df.shape

(19239, 44)

In [5]:
# Clean up the columns
plays_df = plays_df.drop(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1'], axis=1)
plays_df.head()

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,...,week,def,defender,manZone,scheme,route,startDist,endDist,covDist,closeSpeed
0,2018090600,75,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,...,1,PHI,Malcolm Jenkins,zone,cover-3,HITCH,7.768739,2.957871,10.726609,4.369544
1,2018090600,146,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,...,1,PHI,Jordan Hicks,zone,cover-3,HITCH,4.346631,1.891719,6.238350,4.909824
2,2018090600,168,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,...,1,PHI,Sidney Jones,man,cover-1,NaN,NaN,NaN,NaN,NaN
3,2018090600,190,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,...,1,PHI,Ronald Darby,man,cover-1,CORNER,12.974671,3.898949,16.873620,5.341803
4,2018090600,256,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,...,1,PHI,Malcolm Jenkins,man,cover-0,GO,1.053803,4.464135,5.517937,-3.789258

In [6]:
# Drop all rows with Nan values
plays_df = plays_df[plays_df['route'].notna()]
plays_df.head()

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,...,week,def,defender,manZone,scheme,route,startDist,endDist,covDist,closeSpeed
0,2018090600,75,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,...,1,PHI,Malcolm Jenkins,zone,cover-3,HITCH,7.768739,2.957871,10.726609,4.369544
1,2018090600,146,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,...,1,PHI,Jordan Hicks,zone,cover-3,HITCH,4.346631,1.891719,6.238350,4.909824
3,2018090600,190,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,...,1,PHI,Ronald Darby,man,cover-1,CORNER,12.974671,3.898949,16.873620,5.341803
4,2018090600,256,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,...,1,PHI,Malcolm Jenkins,man,cover-0,GO,1.053803,4.464135,5.517937,-3.789258
5,2018090600,320,(10:10) (Shotgun) N.Foles pass short left to N...,1,2,8,PHI,play_type_pass,PHI,4,...,1,ATL,Robert Alford,zone,cover-3,OUT,3.989010,1.417956,5.406966,3.213817

In [7]:
# Check shape of plays df
plays_df.shape

(13023, 41)

In [8]:
# The number of plays for each route
count_df = plays_df.groupby('route')['playId'].count()
count_df.head(10)

route
ANGLE      523
CORNER     336
CROSS     1548
FLAT      1972
GO        1252
HITCH     2032
IN         793
OUT       1913
POST       587
SCREEN    1052
Name: playId, dtype: int64

In [9]:
# The number of completions for each route
completion_df = plays_df.groupby('route')['passResult'].apply(lambda x: (x=='C').sum())
completion_df

route
ANGLE         453
CORNER        235
CROSS        1259
FLAT         1712
GO            766
HITCH        1677
IN            618
OUT          1537
POST          395
SCREEN        995
SLANT         718
WHEEL          71
undefined       9
Name: passResult, dtype: int64

In [10]:
# The number of incompletions for each route
incompletion_df = plays_df.groupby('route')['passResult'].apply(lambda x: (x=='I').sum())
incompletion_df

route
ANGLE         61
CORNER        86
CROSS        269
FLAT         246
GO           436
HITCH        331
IN           164
OUT          350
POST         161
SCREEN        53
SLANT        183
WHEEL         16
undefined      3
Name: passResult, dtype: int64

In [11]:
# The number of interceptions for each route
interception_df = plays_df.groupby('route')['passResult'].apply(lambda x: (x=='IN').sum())
interception_df

route
ANGLE         9
CORNER       15
CROSS        20
FLAT         14
GO           50
HITCH        24
IN           11
OUT          26
POST         31
SCREEN        4
SLANT        13
WHEEL         2
undefined     0
Name: passResult, dtype: int64

In [12]:
# The average epa for each route
epa_df = plays_df.groupby('route')['epa'].mean()
epa_df

route
ANGLE        0.091724
CORNER       0.943995
CROSS        0.453216
FLAT         0.045054
GO           0.736074
HITCH        0.274343
IN           0.576503
OUT          0.321634
POST         0.857922
SCREEN      -0.012289
SLANT        0.353716
WHEEL        1.175763
undefined    0.132117
Name: epa, dtype: float64

In [13]:
# The merged dataframe for the initial stats
merge_list = [count_df, completion_df, incompletion_df, interception_df, epa_df]
route_df = pd.concat(merge_list, axis=1)
route_df.columns = ['totalPassAttempts', 'completions', 'incompletions', 'interceptions', 'epaMean']
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean
0,ANGLE,523,453,61,9,0.091724
1,CORNER,336,235,86,15,0.943995
2,CROSS,1548,1259,269,20,0.453216
3,FLAT,1972,1712,246,14,0.045054
4,GO,1252,766,436,50,0.736074
5,HITCH,2032,1677,331,24,0.274343
6,IN,793,618,164,11,0.576503
7,OUT,1913,1537,350,26,0.321634
8,POST,587,395,161,31,0.857922
9,SCREEN,1052,995,53,4,-0.012289
10,SLANT,914,718,183,13,0.353716
11,WHEEL,89,71,16,2,1.175763
12,undefined,12,9,3,0,0.132117

In [14]:
# Drop the undefined row
route_df.drop(route_df[route_df['totalPassAttempts'] == 12].index, inplace = True)
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean
0,ANGLE,523,453,61,9,0.091724
1,CORNER,336,235,86,15,0.943995
2,CROSS,1548,1259,269,20,0.453216
3,FLAT,1972,1712,246,14,0.045054
4,GO,1252,766,436,50,0.736074
5,HITCH,2032,1677,331,24,0.274343
6,IN,793,618,164,11,0.576503
7,OUT,1913,1537,350,26,0.321634
8,POST,587,395,161,31,0.857922
9,SCREEN,1052,995,53,4,-0.012289
10,SLANT,914,718,183,13,0.353716
11,WHEEL,89,71,16,2,1.175763

In [15]:
# The route completion percentage
route_df['completionPct'] = route_df['completions'] / route_df['totalPassAttempts']
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean,completionPct
0,ANGLE,523,453,61,9,0.091724,0.866157
1,CORNER,336,235,86,15,0.943995,0.699405
2,CROSS,1548,1259,269,20,0.453216,0.813307
3,FLAT,1972,1712,246,14,0.045054,0.868154
4,GO,1252,766,436,50,0.736074,0.611821
5,HITCH,2032,1677,331,24,0.274343,0.825295
6,IN,793,618,164,11,0.576503,0.779319
7,OUT,1913,1537,350,26,0.321634,0.803450
8,POST,587,395,161,31,0.857922,0.672913
9,SCREEN,1052,995,53,4,-0.012289,0.945817
10,SLANT,914,718,183,13,0.353716,0.785558
11,WHEEL,89,71,16,2,1.175763,0.797753

In [16]:
# The route completion rank
route_df['completionRank'] = route_df['completionPct'].rank(ascending=0)
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean,completionPct,completionRank
0,ANGLE,523,453,61,9,0.091724,0.866157,3.0
1,CORNER,336,235,86,15,0.943995,0.699405,10.0
2,CROSS,1548,1259,269,20,0.453216,0.813307,5.0
3,FLAT,1972,1712,246,14,0.045054,0.868154,2.0
4,GO,1252,766,436,50,0.736074,0.611821,12.0
5,HITCH,2032,1677,331,24,0.274343,0.825295,4.0
6,IN,793,618,164,11,0.576503,0.779319,9.0
7,OUT,1913,1537,350,26,0.321634,0.803450,6.0
8,POST,587,395,161,31,0.857922,0.672913,11.0
9,SCREEN,1052,995,53,4,-0.012289,0.945817,1.0
10,SLANT,914,718,183,13,0.353716,0.785558,8.0
11,WHEEL,89,71,16,2,1.175763,0.797753,7.0

In [17]:
# The route epa rank
route_df['epaRank'] = route_df['epaMean'].rank(ascending=0)
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean,completionPct,completionRank,epaRank
0,ANGLE,523,453,61,9,0.091724,0.866157,3.0,10.0
1,CORNER,336,235,86,15,0.943995,0.699405,10.0,2.0
2,CROSS,1548,1259,269,20,0.453216,0.813307,5.0,6.0
3,FLAT,1972,1712,246,14,0.045054,0.868154,2.0,11.0
4,GO,1252,766,436,50,0.736074,0.611821,12.0,4.0
5,HITCH,2032,1677,331,24,0.274343,0.825295,4.0,9.0
6,IN,793,618,164,11,0.576503,0.779319,9.0,5.0
7,OUT,1913,1537,350,26,0.321634,0.803450,6.0,8.0
8,POST,587,395,161,31,0.857922,0.672913,11.0,3.0
9,SCREEN,1052,995,53,4,-0.012289,0.945817,1.0,12.0
10,SLANT,914,718,183,13,0.353716,0.785558,8.0,7.0
11,WHEEL,89,71,16,2,1.175763,0.797753,7.0,1.0

In [18]:
# The route interception percentage
route_df['intPct'] = route_df['interceptions'] / route_df['totalPassAttempts']
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean,completionPct,completionRank,epaRank,intPct
0,ANGLE,523,453,61,9,0.091724,0.866157,3.0,10.0,0.017208
1,CORNER,336,235,86,15,0.943995,0.699405,10.0,2.0,0.044643
2,CROSS,1548,1259,269,20,0.453216,0.813307,5.0,6.0,0.012920
3,FLAT,1972,1712,246,14,0.045054,0.868154,2.0,11.0,0.007099
4,GO,1252,766,436,50,0.736074,0.611821,12.0,4.0,0.039936
5,HITCH,2032,1677,331,24,0.274343,0.825295,4.0,9.0,0.011811
6,IN,793,618,164,11,0.576503,0.779319,9.0,5.0,0.013871
7,OUT,1913,1537,350,26,0.321634,0.803450,6.0,8.0,0.013591
8,POST,587,395,161,31,0.857922,0.672913,11.0,3.0,0.052811
9,SCREEN,1052,995,53,4,-0.012289,0.945817,1.0,12.0,0.003802
10,SLANT,914,718,183,13,0.353716,0.785558,8.0,7.0,0.014223
11,WHEEL,89,71,16,2,1.175763,0.797753,7.0,1.0,0.022472

In [19]:
# The route interception rank
route_df['intRank'] = route_df['intPct'].rank(ascending=1)
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean,completionPct,completionRank,epaRank,intPct,intRank
0,ANGLE,523,453,61,9,0.091724,0.866157,3.0,10.0,0.017208,8.0
1,CORNER,336,235,86,15,0.943995,0.699405,10.0,2.0,0.044643,11.0
2,CROSS,1548,1259,269,20,0.453216,0.813307,5.0,6.0,0.012920,4.0
3,FLAT,1972,1712,246,14,0.045054,0.868154,2.0,11.0,0.007099,2.0
4,GO,1252,766,436,50,0.736074,0.611821,12.0,4.0,0.039936,10.0
5,HITCH,2032,1677,331,24,0.274343,0.825295,4.0,9.0,0.011811,3.0
6,IN,793,618,164,11,0.576503,0.779319,9.0,5.0,0.013871,6.0
7,OUT,1913,1537,350,26,0.321634,0.803450,6.0,8.0,0.013591,5.0
8,POST,587,395,161,31,0.857922,0.672913,11.0,3.0,0.052811,12.0
9,SCREEN,1052,995,53,4,-0.012289,0.945817,1.0,12.0,0.003802,1.0
10,SLANT,914,718,183,13,0.353716,0.785558,8.0,7.0,0.014223,7.0
11,WHEEL,89,71,16,2,1.175763,0.797753,7.0,1.0,0.022472,9.0

In [20]:
# The route combined rank - equal weighting for each ranking
# route_df['combinedRank'] = route_df['completionRank'] + route_df['epaRank'] + route_df['intRank']
# route_df = route_df.sort_values(by=['combinedRank'])
# route_df.reset_index()

In [21]:
route_df.to_excel('/Users/JKMacBook/Documents/Lambda/Kaggle/NFL/nfl-big-data-bowl-2021/routes.xlsx', index=True)