In [1]:
# Imports
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Load the data
plays_df = pd.read_csv('/Users/JKMacBook/Documents/Lambda/Kaggle/NFL/nfl-big-data-bowl-2021/full_play_3.csv')

In [3]:
# Check shape of plays df
plays_df.shape

(19239, 44)

In [4]:
# Clean up the columns
plays_df = plays_df.drop(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1'], axis=1)

In [5]:
# Drop all rows with Nan values
plays_df = plays_df[plays_df['route'].notna()]

In [6]:
# Check shape of plays df
plays_df.shape

(13023, 41)

In [7]:
# The number of plays for each route
count_df = plays_df.groupby('route')['playId'].count()

In [8]:
# The number of completions for each route
completion_df = plays_df.groupby('route')['passResult'].apply(lambda x: (x=='C').sum())

In [9]:
# The number of incompletions for each route
incompletion_df = plays_df.groupby('route')['passResult'].apply(lambda x: (x=='I').sum())

In [10]:
# The number of interceptions for each route
interception_df = plays_df.groupby('route')['passResult'].apply(lambda x: (x=='IN').sum())

In [11]:
# The average epa for each route
epa_df = plays_df.groupby('route')['epa'].mean()

In [12]:
# The merged dataframe for the initial stats
merge_list = [count_df, completion_df, incompletion_df, interception_df, epa_df]
route_df = pd.concat(merge_list, axis=1)
route_df.columns = ['totalPassAttempts', 'completions', 'incompletions', 'interceptions', 'epaMean']
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean
0,ANGLE,523,453,61,9,0.091724
1,CORNER,336,235,86,15,0.943995
2,CROSS,1548,1259,269,20,0.453216
3,FLAT,1972,1712,246,14,0.045054
4,GO,1252,766,436,50,0.736074
5,HITCH,2032,1677,331,24,0.274343
6,IN,793,618,164,11,0.576503
7,OUT,1913,1537,350,26,0.321634
8,POST,587,395,161,31,0.857922
9,SCREEN,1052,995,53,4,-0.012289
10,SLANT,914,718,183,13,0.353716
11,WHEEL,89,71,16,2,1.175763
12,undefined,12,9,3,0,0.132117

In [13]:
# Drop the undefined row
route_df.drop(route_df[route_df['totalPassAttempts'] == 12].index, inplace = True)
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean
0,ANGLE,523,453,61,9,0.091724
1,CORNER,336,235,86,15,0.943995
2,CROSS,1548,1259,269,20,0.453216
3,FLAT,1972,1712,246,14,0.045054
4,GO,1252,766,436,50,0.736074
5,HITCH,2032,1677,331,24,0.274343
6,IN,793,618,164,11,0.576503
7,OUT,1913,1537,350,26,0.321634
8,POST,587,395,161,31,0.857922
9,SCREEN,1052,995,53,4,-0.012289
10,SLANT,914,718,183,13,0.353716
11,WHEEL,89,71,16,2,1.175763

In [14]:
# The route completion percentage
route_df['completionPct'] = route_df['completions'] / route_df['totalPassAttempts']
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean,completionPct
0,ANGLE,523,453,61,9,0.091724,0.866157
1,CORNER,336,235,86,15,0.943995,0.699405
2,CROSS,1548,1259,269,20,0.453216,0.813307
3,FLAT,1972,1712,246,14,0.045054,0.868154
4,GO,1252,766,436,50,0.736074,0.611821
5,HITCH,2032,1677,331,24,0.274343,0.825295
6,IN,793,618,164,11,0.576503,0.779319
7,OUT,1913,1537,350,26,0.321634,0.803450
8,POST,587,395,161,31,0.857922,0.672913
9,SCREEN,1052,995,53,4,-0.012289,0.945817
10,SLANT,914,718,183,13,0.353716,0.785558
11,WHEEL,89,71,16,2,1.175763,0.797753

In [15]:
# The route completion rank
route_df['completionRank'] = route_df['completionPct'].rank(ascending=0)
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean,completionPct,completionRank
0,ANGLE,523,453,61,9,0.091724,0.866157,3.0
1,CORNER,336,235,86,15,0.943995,0.699405,10.0
2,CROSS,1548,1259,269,20,0.453216,0.813307,5.0
3,FLAT,1972,1712,246,14,0.045054,0.868154,2.0
4,GO,1252,766,436,50,0.736074,0.611821,12.0
5,HITCH,2032,1677,331,24,0.274343,0.825295,4.0
6,IN,793,618,164,11,0.576503,0.779319,9.0
7,OUT,1913,1537,350,26,0.321634,0.803450,6.0
8,POST,587,395,161,31,0.857922,0.672913,11.0
9,SCREEN,1052,995,53,4,-0.012289,0.945817,1.0
10,SLANT,914,718,183,13,0.353716,0.785558,8.0
11,WHEEL,89,71,16,2,1.175763,0.797753,7.0

In [16]:
# The route epa rank
route_df['epaRank'] = route_df['epaMean'].rank(ascending=0)
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean,completionPct,completionRank,epaRank
0,ANGLE,523,453,61,9,0.091724,0.866157,3.0,10.0
1,CORNER,336,235,86,15,0.943995,0.699405,10.0,2.0
2,CROSS,1548,1259,269,20,0.453216,0.813307,5.0,6.0
3,FLAT,1972,1712,246,14,0.045054,0.868154,2.0,11.0
4,GO,1252,766,436,50,0.736074,0.611821,12.0,4.0
5,HITCH,2032,1677,331,24,0.274343,0.825295,4.0,9.0
6,IN,793,618,164,11,0.576503,0.779319,9.0,5.0
7,OUT,1913,1537,350,26,0.321634,0.803450,6.0,8.0
8,POST,587,395,161,31,0.857922,0.672913,11.0,3.0
9,SCREEN,1052,995,53,4,-0.012289,0.945817,1.0,12.0
10,SLANT,914,718,183,13,0.353716,0.785558,8.0,7.0
11,WHEEL,89,71,16,2,1.175763,0.797753,7.0,1.0

In [17]:
# The route interception percentage
route_df['intPct'] = route_df['interceptions'] / route_df['totalPassAttempts']
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean,completionPct,completionRank,epaRank,intPct
0,ANGLE,523,453,61,9,0.091724,0.866157,3.0,10.0,0.017208
1,CORNER,336,235,86,15,0.943995,0.699405,10.0,2.0,0.044643
2,CROSS,1548,1259,269,20,0.453216,0.813307,5.0,6.0,0.012920
3,FLAT,1972,1712,246,14,0.045054,0.868154,2.0,11.0,0.007099
4,GO,1252,766,436,50,0.736074,0.611821,12.0,4.0,0.039936
5,HITCH,2032,1677,331,24,0.274343,0.825295,4.0,9.0,0.011811
6,IN,793,618,164,11,0.576503,0.779319,9.0,5.0,0.013871
7,OUT,1913,1537,350,26,0.321634,0.803450,6.0,8.0,0.013591
8,POST,587,395,161,31,0.857922,0.672913,11.0,3.0,0.052811
9,SCREEN,1052,995,53,4,-0.012289,0.945817,1.0,12.0,0.003802
10,SLANT,914,718,183,13,0.353716,0.785558,8.0,7.0,0.014223
11,WHEEL,89,71,16,2,1.175763,0.797753,7.0,1.0,0.022472

In [18]:
# The route interception rank
route_df['intRank'] = route_df['intPct'].rank(ascending=1)
route_df.reset_index()

,route,totalPassAttempts,completions,incompletions,interceptions,epaMean,completionPct,completionRank,epaRank,intPct,intRank
0,ANGLE,523,453,61,9,0.091724,0.866157,3.0,10.0,0.017208,8.0
1,CORNER,336,235,86,15,0.943995,0.699405,10.0,2.0,0.044643,11.0
2,CROSS,1548,1259,269,20,0.453216,0.813307,5.0,6.0,0.012920,4.0
3,FLAT,1972,1712,246,14,0.045054,0.868154,2.0,11.0,0.007099,2.0
4,GO,1252,766,436,50,0.736074,0.611821,12.0,4.0,0.039936,10.0
5,HITCH,2032,1677,331,24,0.274343,0.825295,4.0,9.0,0.011811,3.0
6,IN,793,618,164,11,0.576503,0.779319,9.0,5.0,0.013871,6.0
7,OUT,1913,1537,350,26,0.321634,0.803450,6.0,8.0,0.013591,5.0
8,POST,587,395,161,31,0.857922,0.672913,11.0,3.0,0.052811,12.0
9,SCREEN,1052,995,53,4,-0.012289,0.945817,1.0,12.0,0.003802,1.0
10,SLANT,914,718,183,13,0.353716,0.785558,8.0,7.0,0.014223,7.0
11,WHEEL,89,71,16,2,1.175763,0.797753,7.0,1.0,0.022472,9.0

In [19]:
# The route combined rank - equal weighting for each ranking
# route_df['combinedRank'] = route_df['completionRank'] + route_df['epaRank'] + route_df['intRank']
# route_df = route_df.sort_values(by=['combinedRank'])
# route_df.reset_index()

In [20]:
route_df.to_excel('/Users/JKMacBook/Documents/Lambda/Kaggle/NFL/nfl-big-data-bowl-2021/final/routes.xlsx', index=True)